version: '3'

services:
  livraria-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "l1vr4r14"
      POSTGRES_DB: "livraria"
    ports:
      - "5432:5432"
    volumes:
      - ./data/livraria:/var/lib/postgresql/data 
    networks:
      - livraria-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "orlando.burli@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "JGSaFb2YbmhsN4Yb"
    ports:
      - "5400:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - livraria-db
    networks:
      - livraria-network
  rabbit-server:
    image: rabbitmq:management
    environment:
      - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - livraria-network

networks: 
  livraria-network:
    driver: bridge