version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn test
      - run: mvn clean package -Dbuild=$CIRCLE_BUILD_NUM -Dmaven.test.skip=true
      - store_artifacts:
          path: deploy
workflows:
  api_build:
    jobs: 
      - build:
          filters:
            branches:
              only:
                - master